name: CMake

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: build-linux
    runs-on: ubuntu-latest

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y vim git g++ cmake make libssl-dev libgtest-dev libbrotli-dev
    
    - name: Checkout workflow
      uses: actions/checkout@master
      with:
        repository: sogou/workflow    

    - name: Install workflow
      shell: bash
      run: |
        make -j $(nproc) && sudo make install

    # - name: Checkout googletest
    #   uses: actions/checkout@main
    #   with:
    #     repository: google/googletest 
    
    # - name: Install googletest
    #   shell: bash
    #   working-directory: ./build
    #   run: |
    #     cmake .. && make -j $(nproc) && sudo make install

    - name: Checkout wfrest source code
      uses: actions/checkout@v2

    - name: Create build directory
      run: |
        mkdir build

    - name: Create Build Environment & Configure Cmake
      shell: bash
      working-directory: ./build
      run: |
        cmake .. 

    - name: Build
      working-directory: ./build
      shell: bash
      run: |
        sudo make -j $(nproc) && sudo make install

    - name: Test
      working-directory: ./build
      shell: bash
      run: |
        sudo make test
      
